<?php

define('ARTICLE_STATUS_OPEN', 1);
define('ARTICLE_STATUS_EXCHANGE', 2);
define('ARTICLE_STATUS_CLOSE_ADMIN', 3);
define('ARTICLE_STATUS_CLOSE_USER', 4);
define('ARTICLE_STATUS_EXCHANGE_USER', 5);
define('ARTICLE_STATUS_RETIRED_USER', 6);
define('ARTICLE_STATUS_EXPIRED', 7);

define('ARTICLE_CONDITION_NEW', 1);
define('ARTICLE_CONDITION_USED', 2);
define('ARTICLE_CONDITION_REFURBISHED', 3);

define('QUESTION_STATUS_OPEN', 1);
define('QUESTION_STATUS_HIDE', 2);
define('QUESTION_STATUS_DELETED', 3);

define('OFFER_STATUS_OPEN', 1);
define('OFFER_STATUS_ACCEPTED', 2);
define('OFFER_STATUS_REJECTED', 3);
